[pytest]
DJANGO_SETTINGS_MODULE = django_project.settings
python_files = test_*.py
testpaths = reports/tests

# --reuse-db keeps the test database between runs; pass --create-db to rebuild it
# after a migration.
addopts = --reuse-db
