# Generated by Django 5.2.8 on 2025-11-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The short code for the company (e.g., 'NL').",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the company (e.g., 'NLCIL').",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Code",
                "verbose_name_plural": "Company Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The short code for the project type (e.g., 'S').",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the project type (e.g., 'Service').",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Type",
                "verbose_name_plural": "Project Types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WBSElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wbs_element",
                    models.CharField(
                        db_index=True,
                        help_text="The unique identifier for the WBS element.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The descriptive name of the WBS element.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "WBS Element",
                "verbose_name_plural": "WBS Elements",
                "ordering": ["wbs_element"],
            },
        ),
    ]
