# Generated by Django 5.1.3 on 2025-11-30 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("budget", "Budget Report"),
                            ("budget_updates", "Budget Updates"),
                            ("budget_variance", "Budget Variance"),
                            ("project_type_wise", "Project Type Wise"),
                            ("glimps_of_projects", "Glimps of Projects"),
                            ("plan_variance", "Plan Variance"),
                            ("project_analysis", "Project Analysis"),
                        ],
                        help_text="Type of report generated",
                        max_length=50,
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Name of the generated file", max_length=255
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Full path to the generated file", max_length=500
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Size of the file in bytes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("processing", "Processing"),
                        ],
                        default="success",
                        help_text="Status of report generation",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the report was generated",
                    ),
                ),
                (
                    "rows_processed",
                    models.IntegerField(
                        default=0, help_text="Number of data rows processed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who generated the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report History",
                "verbose_name_plural": "Report Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="reports_rep_created_48ef6c_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="reports_rep_user_id_3a166e_idx",
                    ),
                    models.Index(
                        fields=["report_type", "-created_at"],
                        name="reports_rep_report__e630e5_idx",
                    ),
                ],
            },
        ),
    ]
