# Generated by Django 5.2.8 on 2026-04-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_reporthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="The short code for the document type (e.g., 'AA').",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the document type (e.g., 'Asset Posting').",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "ordering": ["code"],
            },
        ),
    ]
